/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppDetails {
        "heading": String;
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface PageFooter {
    }
    interface ProposalCard {
        "description": string;
        "dismissSnackbar": () => Promise<void>;
        "expirationDate": Date;
        "hasVoted": boolean;
        "heading": string;
        "nay": number;
        "setLoading": () => Promise<void>;
        "totalVotes": number;
        "yay": number;
    }
    interface ProposalForm {
    }
    interface WalletButton {
        "connected": boolean;
    }
}
declare global {
    interface HTMLAppDetailsElement extends Components.AppDetails, HTMLStencilElement {
    }
    var HTMLAppDetailsElement: {
        prototype: HTMLAppDetailsElement;
        new (): HTMLAppDetailsElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPageFooterElement extends Components.PageFooter, HTMLStencilElement {
    }
    var HTMLPageFooterElement: {
        prototype: HTMLPageFooterElement;
        new (): HTMLPageFooterElement;
    };
    interface HTMLProposalCardElement extends Components.ProposalCard, HTMLStencilElement {
    }
    var HTMLProposalCardElement: {
        prototype: HTMLProposalCardElement;
        new (): HTMLProposalCardElement;
    };
    interface HTMLProposalFormElement extends Components.ProposalForm, HTMLStencilElement {
    }
    var HTMLProposalFormElement: {
        prototype: HTMLProposalFormElement;
        new (): HTMLProposalFormElement;
    };
    interface HTMLWalletButtonElement extends Components.WalletButton, HTMLStencilElement {
    }
    var HTMLWalletButtonElement: {
        prototype: HTMLWalletButtonElement;
        new (): HTMLWalletButtonElement;
    };
    interface HTMLElementTagNameMap {
        "app-details": HTMLAppDetailsElement;
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "page-footer": HTMLPageFooterElement;
        "proposal-card": HTMLProposalCardElement;
        "proposal-form": HTMLProposalFormElement;
        "wallet-button": HTMLWalletButtonElement;
    }
}
declare namespace LocalJSX {
    interface AppDetails {
        "heading"?: String;
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface PageFooter {
    }
    interface ProposalCard {
        "description"?: string;
        "expirationDate"?: Date;
        "hasVoted"?: boolean;
        "heading"?: string;
        "nay"?: number;
        "onCastVote"?: (event: CustomEvent<any>) => void;
        "totalVotes"?: number;
        "yay"?: number;
    }
    interface ProposalForm {
    }
    interface WalletButton {
        "connected"?: boolean;
        "onConnect"?: (event: CustomEvent<any>) => void;
        "onDisconnect"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "app-details": AppDetails;
        "app-home": AppHome;
        "app-root": AppRoot;
        "page-footer": PageFooter;
        "proposal-card": ProposalCard;
        "proposal-form": ProposalForm;
        "wallet-button": WalletButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-details": LocalJSX.AppDetails & JSXBase.HTMLAttributes<HTMLAppDetailsElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "page-footer": LocalJSX.PageFooter & JSXBase.HTMLAttributes<HTMLPageFooterElement>;
            "proposal-card": LocalJSX.ProposalCard & JSXBase.HTMLAttributes<HTMLProposalCardElement>;
            "proposal-form": LocalJSX.ProposalForm & JSXBase.HTMLAttributes<HTMLProposalFormElement>;
            "wallet-button": LocalJSX.WalletButton & JSXBase.HTMLAttributes<HTMLWalletButtonElement>;
        }
    }
}
